version: '3'
services:
    nuxt:
        build: ./app/
        container_name: nuxt
        restart: always
        ports:
            - "3000:3000"
        command: "npm run start"

    nginx:
        image: nginx:1.13
        container_name: nginx
        restart: always
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 80:80
        depends_on:
            - nuxt
